version: "3"

services:

  #Application Service
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:9000'
    volumes:
      - ./:/var/www
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      DATABASE_URL: mysql://my_user:my_password@db:3306/my_database
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_CONFIG: "start_with_request=yes client_port=9000"
      XDEBUG_MODE: "debug"
    depends_on:
      - db

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - app

  #Database Service
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_root_password
    ports:
      - '3307:3306'
    volumes:
      - ./.docker/data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf

  #Database Test Service
  db_test:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: my_database_test
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_root_password
    ports:
      - '3308:3306'
    volumes:
      - ./.docker/data_test:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf

  #phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - PMA_HOST=db
      - PMA_ARBITRARY=0
    ports:
      - 7778:80

volumes:
  database_data:
  database_data_test:
