version: '3'

services:
###> doctrine/doctrine-bundle ###
  db:
    ports:
      - "3307"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
