#!/bin/bash

echo "   ______     _       __    __"
echo "  / ____/____(_)___  / /_  / /_"
echo " / / __/ ___/ / __ \/ __ \/ __ \\"
echo "/ /_/ / /  / / /_/ / /_/ / /_/ /"
echo "\____/_/  /_/ .___/_.___/_.___/"
echo "           /_/"
echo
echo "Starting setup..."
echo

sleep 1

if ! grep -q "flanderijn.gripbb.local" /etc/hosts; then
  echo "# Added by Gripbb" | sudo tee -a /etc/hosts > /dev/null
  echo "127.0.0.1:80 flanderijn.gripbb.local" | sudo tee -a /etc/hosts > /dev/null
  echo "# END Gripbb section" | sudo tee -a /etc/hosts > /dev/null
fi

cp .env.local.dist .env.local

docker compose up -d

while [[ "$(docker-compose ps -q | xargs docker inspect --format='{{.State.Status}}')" != *"Up"* ]]; do
    sleep 1
done

echo "All containers are up and running."

docker compose exec -it php bin/console gripbb:create:testusers
docker compose exec -it php bin/console fos:elastica:populate

echo "Gripbb running on: flanderijn.gripbb.local"
